package it.aboutbits.springboot.emailservice.lib.application;

import lombok.extern.slf4j.Slf4j;
import org.springframework.jdbc.core.JdbcTemplate;

@Slf4j
public class EmailServiceMigrator {
    private final JdbcTemplate jdbcTemplate;

    public EmailServiceMigrator(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    void init() {
        log.info("EmailService: running DB migrations...");

        jdbcTemplate.execute("""

                 create table if not exists email_service_emails
                 (
                     id                   bigint generated by default as identity
                         primary key,
                     state                text                     default 'PENDING'::text not null,
                     subject              text                                             not null,
                     recipients           jsonb                                            not null,
                     from_address         text                                             not null,
                     from_name            text                                             not null,
                     text_body            text                                             not null,
                     html_body            text                                             not null,
                     attachments          jsonb                    default '[]'::jsonb,
                     sending_scheduled_at timestamp with time zone default now()           not null,
                     reference            text,
                     sent_at              timestamp with time zone,
                     error_at             timestamp with time zone,
                     error_message        text,
                     created_at           timestamp with time zone default now()           not null,
                     updated_at           timestamp with time zone default now()           not null,
                     constraint email_service_emails_one_body_not_empty
                         check ((text_body <> ''::text) OR (html_body <> ''::text))
                 );

                 create index if not exists email_service_emails_reference_index
                     on email_service_emails (reference);

                 create index if not exists email_service_emails_state_index
                     on email_service_emails (state);

                 create index if not exists email_service_emails_sending_scheduled_at_index
                     on email_service_emails (sending_scheduled_at);

                 create table if not exists email_service_email_attachments
                 (
                     id           bigint generated by default as identity
                         primary key,
                     email_id     bigint not null
                         constraint email_service_email_attachments_email_id
                             references email_service_emails,
                     file_name    text   not null,
                     content_type text   not null,
                     reference    text   not null
                 );

                 create index if not exists email_service_email_attachments_email_id_index
                     on email_service_email_attachments (email_id);

                """);

        log.info("EmailService: done!");
    }
}
