package it.aboutbits.springboot.emailservice.lib.application;

import it.aboutbits.springboot.emailservice.lib.AttachmentDataSource;
import it.aboutbits.springboot.emailservice.lib.exception.AttachmentException;
import lombok.extern.slf4j.Slf4j;
import org.jspecify.annotations.NullMarked;
import org.springframework.dao.DataAccessException;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;

@Slf4j
@NullMarked
public class JdbcAttachmentDataSource implements AttachmentDataSource {
    private final JdbcTemplate jdbcTemplate;

    public JdbcAttachmentDataSource(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void migrate() {
        log.info("EmailService: running attachment payload DB migrations...");

        jdbcTemplate.execute(
                //@formatter:off
                """

                 create table if not exists email_service_attachment_payloads
                 (
                     id bigint generated by default as identity
                               primary key,
                     payload bytea not null,
                     created_at timestamp with time zone default now() not null
                 );
                """
                //@formatter:on
        );

        log.info("EmailService: attachment payload migrations done!");
    }

    @Override
    public InputStream getAttachmentPayload(long fileReference) throws AttachmentException {
        try {
            var payload = jdbcTemplate.queryForObject(
                    "select payload from email_service_attachment_payloads where id = ?",
                    byte[].class,
                    fileReference
            );
            if (payload == null) {
                throw new AttachmentException("attachment payload not found: " + fileReference);
            }
            return new ByteArrayInputStream(payload);
        } catch (EmptyResultDataAccessException e) {
            throw new AttachmentException("attachment payload not found: " + fileReference, e);
        } catch (DataAccessException e) {
            throw new AttachmentException("failed to load attachment payload: " + fileReference, e);
        }
    }

    @Override
    public long storeAttachmentPayload(InputStream payload) throws AttachmentException {
        final byte[] bytes;
        try (payload) {
            bytes = payload.readAllBytes();
        } catch (IOException e) {
            throw new AttachmentException("failed to read attachment payload", e);
        }

        try {
            var id = jdbcTemplate.queryForObject(
                    "insert into email_service_attachment_payloads (payload) values (?) returning id",
                    Long.class,
                    (Object) bytes
            );
            if (id == null) {
                throw new AttachmentException("failed to store attachment payload");
            }
            return id;
        } catch (DataAccessException e) {
            throw new AttachmentException("failed to store attachment payload", e);
        }
    }

    @Override
    public void releaseAttachment(long fileReference) throws AttachmentException {
        try {
            jdbcTemplate.update(
                    "delete from email_service_attachment_payloads where id = ?",
                    fileReference
            );
        } catch (DataAccessException e) {
            throw new AttachmentException("failed to release attachment payload: " + fileReference, e);
        }
    }
}
